apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  namespace: poc
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
