apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: poc
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
data:
  POSTGRES_PASSWORD: YWRtaW4=
